FROM ubuntu:20.04

ARG KEA_VERSION=2.2.0
ARG DEBIAN_FRONTEND=noninteractive

ARG KEA_REPO
ARG KEA_VERSION
RUN wget --no-verbose -O- https://dl.cloudsmith.io/${KEA_REPO}/cfg/setup/bash.deb.sh | bash \
        && apt-get update \
        && apt-get install \
        --no-install-recommends \
        -y \
        python3-isc-kea-connector=${KEA_VERSION} \
        isc-kea-ctrl-agent=${KEA_VERSION} \
        isc-kea-dhcp4-server=${KEA_VERSION} \
        isc-kea-dhcp6-server=${KEA_VERSION} \
        isc-kea-admin=${KEA_VERSION} \
        isc-kea-common=${KEA_VERSION} \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/* \
        && mkdir -p /var/run/kea/ \