name: CI Production
on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3
      - name: Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: psf/black@stable
        with:
          options: "--check --verbose --diff"
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.5.1"
      - name: Build Poetry
        run: poetry build
      - name: Publish Package
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
        

